version: '2'
services:
  app_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: als/app_server
    container_name: "als_app_server"
    volumes:
     - .:/home
    ports:
     - "3000:3000"
    links:
     - app_mongo_database

  app_mongo_database:
    image: mongo:latest
    container_name: "als_app_mongodb"
    volumes:
      - ./tmp/data/db:/data/db
    ports:
        - 27017:27017

